### ISSUE TITLE
font rotation 90 degrees

### ISSUE THREAD

**Issue by martinpihrt** [mrnick1234567/miniclock#1]
Hello,
please, give me an advice...
I have a Chinese display max72 ... http://www.elecrow.com/blog/wp-content/uploads/2013/06/MAX7219-8x8-Matrix-Display-Module-Red-Dot1.jpg, but I need to turn all fonts about 90 degrees. Can you help me please?
These LED panels can not access each other and I must therefore have under him as it is here:
https://www.google.cz/url?sa=i&rct=j&q=&esrc=s&source=imgres&cd=&cad=rja&uact=8&ved=0ahUKEwjWgqSNy7XKAhVFshQKHVs2ACYQjRwICTAA&url=https%3A%2F%2Fbrainy-bits.com%2Ftutorials%2Fscroll-text-using-the-max7219-led-dot-matrix%2F&psig=AFQjCNH_EzcIdSXsZOsED77LwHV5NVIxNA&ust=1453282975405617

Thank you Martin

**Comment by mrnick1234567** [comment]
So sorry for the long time to reply. You can usually fix things by tinkering with the function "plot" in the code. Look for the comment "plot a point on the display" and the line starting "void plot". Switch the x and y in the 2 lines that start " lc.setLed(address, y, x, true ); and  lc.setLed(address, y, x, false);". This will plot the pixels 90 degrees around.

**Comment by martinpihrt** [comment]
Ok, thanks
